"""Create initial tables

Revision ID: 418e9783e47d
Revises: 
Create Date: 2024-10-19 20:07:05.104038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '418e9783e47d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_analysis',
    sa.Column('id', sa.UUID(), nullable=False, comment='The unique identifier assigned to a question analysis.'),
    sa.Column('question_text', sa.Text(), nullable=False, comment='The text of the analyzed question.'),
    sa.Column('category', sa.String(length=255), nullable=False, comment='The category of the question.'),
    sa.Column('expertise_rating', sa.Integer(), nullable=False, comment='The expertise rating of the question.'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='The creation date of the question analysis.'),
    sa.Column('knowledge_gaps', sa.ARRAY(sa.Text()), nullable=False, comment='The identified knowledge gaps in the question.'),
    sa.Column('recommendations', sa.ARRAY(sa.Text()), nullable=False, comment='The recommendations based on the question analysis.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_analysis')
    # ### end Alembic commands ###
